declare module "@editorjs/header"
declare module "@editorjs/list"
declare module "@editorjs/simple-image"
declare module "@editorjs/checklist"
declare module "@editorjs/raw"
declare module "@editorjs/inline-code"
declare module "@editorjs/table"
declare module "@editorjs/paragraph"
