import type { Metadata } from "next"
import { Lexend } from "next/font/google"
import "./globals.css"

const lexend = Lexend({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={lexend.className + " bg-zinc-50"}>
        <main className="mx-auto max-w-3xl w-11/12 py-12 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  )
}
